// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.invisiblewrench.fluttermidicommand.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class MidiDeviceType(val raw: Int) {
  SERIAL(0),
  BLE(1),
  VIRTUAL_DEVICE(2),
  OWN_VIRTUAL(3),
  NETWORK(4),
  UNKNOWN(5);

  companion object {
    fun ofRaw(raw: Int): MidiDeviceType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MidiSetupChange(val raw: Int) {
  DEVICE_APPEARED(0),
  DEVICE_DISAPPEARED(1),
  DEVICE_STATE_CHANGED(2),
  DEVICE_CONNECTED(3),
  DEVICE_DISCONNECTED(4);

  companion object {
    fun ofRaw(raw: Int): MidiSetupChange? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MidiHostDevice (
  val id: String? = null,
  val name: String? = null,
  val type: MidiDeviceType? = null,
  val connected: Boolean? = null,
  val inputs: List<MidiPort?>? = null,
  val outputs: List<MidiPort?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MidiHostDevice {
      val id = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val type = pigeonVar_list[2] as MidiDeviceType?
      val connected = pigeonVar_list[3] as Boolean?
      val inputs = pigeonVar_list[4] as List<MidiPort?>?
      val outputs = pigeonVar_list[5] as List<MidiPort?>?
      return MidiHostDevice(id, name, type, connected, inputs, outputs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      type,
      connected,
      inputs,
      outputs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MidiPort (
  val id: Long? = null,
  val connected: Boolean? = null,
  val isInput: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MidiPort {
      val id = pigeonVar_list[0] as Long?
      val connected = pigeonVar_list[1] as Boolean?
      val isInput = pigeonVar_list[2] as Boolean?
      return MidiPort(id, connected, isInput)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      connected,
      isInput,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MidiPacket (
  val device: MidiHostDevice? = null,
  val data: ByteArray? = null,
  val timestamp: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MidiPacket {
      val device = pigeonVar_list[0] as MidiHostDevice?
      val data = pigeonVar_list[1] as ByteArray?
      val timestamp = pigeonVar_list[2] as Long?
      return MidiPacket(device, data, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      device,
      data,
      timestamp,
    )
  }
}
private open class MidiApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MidiDeviceType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MidiSetupChange.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MidiHostDevice.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MidiPort.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MidiPacket.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MidiDeviceType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is MidiSetupChange -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is MidiHostDevice -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is MidiPort -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MidiPacket -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MidiHostApi {
  fun listDevices(): List<MidiHostDevice>
  fun connect(device: MidiHostDevice, ports: List<MidiPort>?)
  fun disconnect(deviceId: String)
  fun teardown()
  fun sendData(packet: MidiPacket)
  fun addVirtualDevice(name: String?)
  fun removeVirtualDevice(name: String?)
  fun isNetworkSessionEnabled(): Boolean?
  fun setNetworkSessionEnabled(enabled: Boolean)

  companion object {
    /** The codec used by MidiHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MidiApiPigeonCodec()
    }
    /** Sets up an instance of `MidiHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MidiHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.listDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listDevices())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceArg = args[0] as MidiHostDevice
            val portsArg = args[1] as List<MidiPort>?
            val wrapped: List<Any?> = try {
              api.connect(deviceArg, portsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.disconnect(deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.teardown$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.teardown()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.sendData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packetArg = args[0] as MidiPacket
            val wrapped: List<Any?> = try {
              api.sendData(packetArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.addVirtualDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.addVirtualDevice(nameArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.removeVirtualDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.removeVirtualDevice(nameArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.isNetworkSessionEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isNetworkSessionEnabled())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.setNetworkSessionEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setNetworkSessionEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class MidiFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MidiFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MidiApiPigeonCodec()
    }
  }
  fun onSetupChanged(setupChangeArg: MidiSetupChange, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onSetupChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(setupChangeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDataReceived(packetArg: MidiPacket, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDataReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(packetArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDeviceConnectionStateChanged(deviceIdArg: String, connectedArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDeviceConnectionStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, connectedArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
