// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum MidiDeviceType: Int {
  case serial = 0
  case ble = 1
  case virtualDevice = 2
  case ownVirtual = 3
  case network = 4
  case unknown = 5
}

enum MidiSetupChange: Int {
  case deviceAppeared = 0
  case deviceDisappeared = 1
  case deviceStateChanged = 2
  case deviceConnected = 3
  case deviceDisconnected = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct MidiHostDevice {
  var id: String? = nil
  var name: String? = nil
  var type: MidiDeviceType? = nil
  var connected: Bool? = nil
  var inputs: [MidiPort?]? = nil
  var outputs: [MidiPort?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MidiHostDevice? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let type: MidiDeviceType? = nilOrValue(pigeonVar_list[2])
    let connected: Bool? = nilOrValue(pigeonVar_list[3])
    let inputs: [MidiPort?]? = nilOrValue(pigeonVar_list[4])
    let outputs: [MidiPort?]? = nilOrValue(pigeonVar_list[5])

    return MidiHostDevice(
      id: id,
      name: name,
      type: type,
      connected: connected,
      inputs: inputs,
      outputs: outputs
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      type,
      connected,
      inputs,
      outputs,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MidiPort {
  var id: Int64? = nil
  var connected: Bool? = nil
  var isInput: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MidiPort? {
    let id: Int64? = nilOrValue(pigeonVar_list[0])
    let connected: Bool? = nilOrValue(pigeonVar_list[1])
    let isInput: Bool? = nilOrValue(pigeonVar_list[2])

    return MidiPort(
      id: id,
      connected: connected,
      isInput: isInput
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      connected,
      isInput,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MidiPacket {
  var device: MidiHostDevice? = nil
  var data: FlutterStandardTypedData? = nil
  var timestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MidiPacket? {
    let device: MidiHostDevice? = nilOrValue(pigeonVar_list[0])
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let timestamp: Int64? = nilOrValue(pigeonVar_list[2])

    return MidiPacket(
      device: device,
      data: data,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      device,
      data,
      timestamp,
    ]
  }
}

private class MidiApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MidiDeviceType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MidiSetupChange(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return MidiHostDevice.fromList(self.readValue() as! [Any?])
    case 132:
      return MidiPort.fromList(self.readValue() as! [Any?])
    case 133:
      return MidiPacket.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MidiApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MidiDeviceType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? MidiSetupChange {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? MidiHostDevice {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MidiPort {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MidiPacket {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MidiApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MidiApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MidiApiPigeonCodecWriter(data: data)
  }
}

class MidiApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MidiApiPigeonCodec(readerWriter: MidiApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MidiHostApi {
  func listDevices() throws -> [MidiHostDevice]
  func connect(device: MidiHostDevice, ports: [MidiPort]?) throws
  func disconnect(deviceId: String) throws
  func teardown() throws
  func sendData(packet: MidiPacket) throws
  func addVirtualDevice(name: String?) throws
  func removeVirtualDevice(name: String?) throws
  func isNetworkSessionEnabled() throws -> Bool?
  func setNetworkSessionEnabled(enabled: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MidiHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MidiApiPigeonCodec.shared }
  /// Sets up an instance of `MidiHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MidiHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let listDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.listDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listDevicesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.listDevices()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listDevicesChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceArg = args[0] as! MidiHostDevice
        let portsArg: [MidiPort]? = nilOrValue(args[1])
        do {
          try api.connect(device: deviceArg, ports: portsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        do {
          try api.disconnect(deviceId: deviceIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let teardownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.teardown\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      teardownChannel.setMessageHandler { _, reply in
        do {
          try api.teardown()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      teardownChannel.setMessageHandler(nil)
    }
    let sendDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.sendData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let packetArg = args[0] as! MidiPacket
        do {
          try api.sendData(packet: packetArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendDataChannel.setMessageHandler(nil)
    }
    let addVirtualDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.addVirtualDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addVirtualDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg: String? = nilOrValue(args[0])
        do {
          try api.addVirtualDevice(name: nameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addVirtualDeviceChannel.setMessageHandler(nil)
    }
    let removeVirtualDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.removeVirtualDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeVirtualDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg: String? = nilOrValue(args[0])
        do {
          try api.removeVirtualDevice(name: nameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeVirtualDeviceChannel.setMessageHandler(nil)
    }
    let isNetworkSessionEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.isNetworkSessionEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isNetworkSessionEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isNetworkSessionEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isNetworkSessionEnabledChannel.setMessageHandler(nil)
    }
    let setNetworkSessionEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.setNetworkSessionEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNetworkSessionEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setNetworkSessionEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNetworkSessionEnabledChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MidiFlutterApiProtocol {
  func onSetupChanged(setupChange setupChangeArg: MidiSetupChange, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDataReceived(packet packetArg: MidiPacket, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDeviceConnectionStateChanged(deviceId deviceIdArg: String, connected connectedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MidiFlutterApi: MidiFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MidiApiPigeonCodec {
    return MidiApiPigeonCodec.shared
  }
  func onSetupChanged(setupChange setupChangeArg: MidiSetupChange, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onSetupChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([setupChangeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDataReceived(packet packetArg: MidiPacket, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDataReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([packetArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDeviceConnectionStateChanged(deviceId deviceIdArg: String, connected connectedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDeviceConnectionStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg, connectedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
