// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum MidiDeviceType {
  serial,
  ble,
  virtualDevice,
  ownVirtual,
  network,
  unknown,
}

enum MidiSetupChange {
  deviceAppeared,
  deviceDisappeared,
  deviceStateChanged,
  deviceConnected,
  deviceDisconnected,
}

class MidiHostDevice {
  MidiHostDevice({
    this.id,
    this.name,
    this.type,
    this.connected,
    this.inputs,
    this.outputs,
  });

  String? id;

  String? name;

  MidiDeviceType? type;

  bool? connected;

  List<MidiPort?>? inputs;

  List<MidiPort?>? outputs;

  Object encode() {
    return <Object?>[
      id,
      name,
      type,
      connected,
      inputs,
      outputs,
    ];
  }

  static MidiHostDevice decode(Object result) {
    result as List<Object?>;
    return MidiHostDevice(
      id: result[0] as String?,
      name: result[1] as String?,
      type: result[2] as MidiDeviceType?,
      connected: result[3] as bool?,
      inputs: (result[4] as List<Object?>?)?.cast<MidiPort?>(),
      outputs: (result[5] as List<Object?>?)?.cast<MidiPort?>(),
    );
  }
}

class MidiPort {
  MidiPort({
    this.id,
    this.connected,
    this.isInput,
  });

  int? id;

  bool? connected;

  bool? isInput;

  Object encode() {
    return <Object?>[
      id,
      connected,
      isInput,
    ];
  }

  static MidiPort decode(Object result) {
    result as List<Object?>;
    return MidiPort(
      id: result[0] as int?,
      connected: result[1] as bool?,
      isInput: result[2] as bool?,
    );
  }
}

class MidiPacket {
  MidiPacket({
    this.device,
    this.data,
    this.timestamp,
  });

  MidiHostDevice? device;

  Uint8List? data;

  int? timestamp;

  Object encode() {
    return <Object?>[
      device,
      data,
      timestamp,
    ];
  }

  static MidiPacket decode(Object result) {
    result as List<Object?>;
    return MidiPacket(
      device: result[0] as MidiHostDevice?,
      data: result[1] as Uint8List?,
      timestamp: result[2] as int?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is MidiDeviceType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is MidiSetupChange) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is MidiHostDevice) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is MidiPort) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is MidiPacket) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : MidiDeviceType.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : MidiSetupChange.values[value];
      case 131: 
        return MidiHostDevice.decode(readValue(buffer)!);
      case 132: 
        return MidiPort.decode(readValue(buffer)!);
      case 133: 
        return MidiPacket.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MidiHostApi {
  /// Constructor for [MidiHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MidiHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<MidiHostDevice>> listDevices() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.listDevices$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<MidiHostDevice>();
    }
  }

  Future<void> connect(MidiHostDevice device, List<MidiPort>? ports) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.connect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[device, ports]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disconnect(String deviceId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[deviceId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> teardown() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.teardown$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> sendData(MidiPacket packet) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.sendData$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packet]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> addVirtualDevice(String? name) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.addVirtualDevice$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[name]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> removeVirtualDevice(String? name) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.removeVirtualDevice$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[name]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool?> isNetworkSessionEnabled() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.isNetworkSessionEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as bool?);
    }
  }

  Future<void> setNetworkSessionEnabled(bool enabled) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiHostApi.setNetworkSessionEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[enabled]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class MidiFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onSetupChanged(MidiSetupChange setupChange);

  void onDataReceived(MidiPacket packet);

  void onDeviceConnectionStateChanged(String deviceId, bool connected);

  static void setUp(MidiFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onSetupChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onSetupChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MidiSetupChange? arg_setupChange = (args[0] as MidiSetupChange?);
          assert(arg_setupChange != null,
              'Argument for dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onSetupChanged was null, expected non-null MidiSetupChange.');
          try {
            api.onSetupChanged(arg_setupChange!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDataReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDataReceived was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MidiPacket? arg_packet = (args[0] as MidiPacket?);
          assert(arg_packet != null,
              'Argument for dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDataReceived was null, expected non-null MidiPacket.');
          try {
            api.onDataReceived(arg_packet!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDeviceConnectionStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDeviceConnectionStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_deviceId = (args[0] as String?);
          assert(arg_deviceId != null,
              'Argument for dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDeviceConnectionStateChanged was null, expected non-null String.');
          final bool? arg_connected = (args[1] as bool?);
          assert(arg_connected != null,
              'Argument for dev.flutter.pigeon.flutter_midi_command_platform_interface.MidiFlutterApi.onDeviceConnectionStateChanged was null, expected non-null bool.');
          try {
            api.onDeviceConnectionStateChanged(arg_deviceId!, arg_connected!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
